quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/quotesapp/urls.py
from django.urls import path
from . import views


app_name = 'quotesapp'

urlpatterns = [
#    path('', views.index, name='index'),
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('author_detail/<int:author_id>', views.author_detail, name='author_detail'),
    path('quote_detail/<int:quote_id>', views.quote_detail, name='quote_detail'),
]

quotes/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

quotes/quotesapp/models.py
from django.db import models

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=35, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    fullname = models.CharField(max_length=25, null=False)
    born_date = models.CharField(max_length=25, null=False)
    born_location = models.CharField(null=False)
    description= models.TextField()

    # def __str__(self):
    #     return f"{self.fullname}"


class Quote(models.Model):
    tags = models.ManyToManyField(Tag)
    # author = models.CharField(max_length=150, null=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.TextField()

    # def __str__(self):
        # return f"{self.name}"

quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea
from .models import Tag, Author, Quote

class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):
    
    fullname = CharField(min_length=3, max_length=25, required=True, 
                                            widget=TextInput())
    
    born_date = CharField(min_length=3, max_length=25, required=True, 
                                            widget=TextInput())
    
    born_location = CharField(min_length=3, max_length=25, required=True, 
                                            widget=TextInput())
    
    description = CharField(min_length=3, max_length=1024, required=True,
                                            widget=Textarea(attrs={"rows":"5"}))
    
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description' ]
 

class QuoteForm(ModelForm):
    
    quote = CharField(min_length=3, max_length=1024, required=True,
                                                widget=Textarea(attrs={"rows":"5"}))
    
    class Meta:
        model = Quote
        fields = [ 'quote' ]
        exclude = [ 'author', 'tags']
        
 

quotes/quotesapp/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
# from django.views.generic import ListView

#from django.http import HttpResponse

from .models import Tag, Author, Quote
from .forms import TagForm, AuthorForm, QuoteForm


# class QuoteListView(ListView):
#     paginate_by = 2
#     model = Quote

# def index(request):
#     return HttpResponse("Hello, world. Quotes App Page.")

def main(request):
    
    # dostęp do listy tylko dla zalogowanych
    # ale w tym projekcie jest on dostępny dla wszystkich
    #quote_list = Quote.objects.all() if request.user.is_authenticated else []
    
    quote_list = Quote.objects.all()
    paginator = Paginator(quote_list, 10)
    
    page_number = request.GET.get("page")
    quotes = paginator.get_page(page_number)
    return render(request, 'quotesapp/index.html', {'quotes': quotes})
    

@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/tag.html', {'form': form})

    return render(request, 'quotesapp/tag.html', {'form': TagForm()})


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/author.html', {'form': form})

    return render(request, 'quotesapp/author.html', {'form': AuthorForm()})

@login_required
def quote(request):
    tags = Tag.objects.all()
    author = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            
            # author assign
            choice_author = Author.objects.get(fullname__in=request.POST.getlist('author'))
            new_quote.author = choice_author
            new_quote.save()
            
            # # tags assigns
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(*choice_tags)
            
            # print("DEBUG choice_author:", choice_author)
            # print("DEBUG quote:", new_quote.quote)
            # print("DEBUG tags:", choice_tags)

            # print("DEBUG new_quote.author:", new_quote.author)
            # print("DEBUG new_quote.quote:", new_quote.quote)
            # print("DEBUG new_quote.tags:", new_quote.tags)

            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/quote.html', {"tags": tags, "author": author, 'form': form})

    return render(request, 'quotesapp/quote.html', {"tags": tags, "author": author, 'form': QuoteForm()})


def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotesapp/author_detail.html', {"author": author})


def quote_detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quotesapp/quote_detail.html', {"quote": quote})

quotes/quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:author' %}">
    {% csrf_token %}
    
    <div style="padding: 10px">
        <label>Enter the full name:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>

    <div style="padding: 10px">
        <label>Enter the born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    
    <div style="padding: 10px">
        <label>Enter the born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>

    <div style="padding: 10px">
        <label>Description (max 1024 chars):
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
   
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>

{% endblock %}

quotes/quotesapp/templates/quotesapp/author_detail.html
{% extends "quotesapp/base.html" %} 

{% block content %}

<h1>{{author.fullname}}</h1>

<p>Born date: <kbd>{{author.born_date}}</kbd> </p>

<p>Born location: {{author.born_location}}</p>

<p>Description:
<span>
    {{author.description}}
</span>
</p>

{% endblock %}

quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPEhtml>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    
	{% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/quotesapp/templates/quotesapp/index.html
{% load extract_tags %}

<!DOCTYPEhtml>
<html lang="en">

<head>
    <meta charset="UTF-8"/>
    <title>Quotes mini WWW page</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>

<main class="container">
    <h1>Quotes in Django</h1>
    
    
    

    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quotesapp:tag' %}" role="button">Add Tag</a></li>
            <li><a href="{% url 'quotesapp:author' %}" role="button">Add Author</a></li>
            <li><a href="{% url 'quotesapp:quote' %}" role="button">Add Quote</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>              
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>

    
   {% for q in quotes %}
    <p>
    Quote id: {{q.pk}} <br> 
    author_id: {{q.author_id}}, <a href="{% url 'quotesapp:author_detail' q.author.pk %}" role="button" class="outline"> {{q.author.fullname}}  </a>  <br>
    quote_test: {{q.quote}} <br>
    Tags:  <small> {{ q.tags|tags }} </small> <br>
    </p>
   {% endfor %}    

    <div class="pagination">
        <span class="step-links">
            {% if quotes.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ quotes.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}.
            </span>
    
            {% if quotes.has_next %}
                <a href="?page={{ quotes.next_page_number }}">next</a>
                <a href="?page={{ quotes.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

   <hr style="width:95%;text-align:center;margin-left:0"> 
    
</main>

</body>
</html>

quotes/quotesapp/templates/quotesapp/quote.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:quote' %}">
    {% csrf_token %}
    
    <div style="padding: 10px">
        <label>Author:
            <select name="author" required>
                {% for a in author %}
                <option value="{{a.fullname}}">{{a.fullname}}</option>
                {% endfor %}        
            </select>
        </label>
        <span>{{ form.errors.author }}</span>
    </div>

    <div style="padding: 10px">
        <label>Tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>


    <div style="padding: 10px">
        <label>Quote:
            {{form.quote}}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
   
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>

{% endblock %}

quotes/quotesapp/templates/quotesapp/quote_detail.html
{% extends "quotesapp/base.html" %} {% load extract_tags %}

{% block content %}

<h1>Quote ID: {{ quote.id }}</h1>

<p>Author ID: <kbd>{{ quote.author.fullname }}</kbd> </p>

<p>Quote tags:  <small> {{ quote.tags|tags }} </small>  </p>

<p>Quote:
<span>
    {{quote.quote}}
</span>
</p>

{% endblock %}

quotes/quotesapp/templates/quotesapp/tag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:tag' %}">

    {% csrf_token %}

    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>

{% endblock %}